version: '3.8'
services:

  ### Mediscreeen container
  mediscreen:
    image: mediscreen
    container_name: mediscreen-container
    build:
      context: . # Point to the root directory
      dockerfile: MediScreenFront/Dockerfile
    ports:
      - "8081:80"
    networks:
      -  mediscreen-network
  
  ### Api container
  api:
    image: api
    container_name: api-container
    environment:
      "MONGODB_CONNECTIONSTRING": "mongodb+srv://MediscreenUser:BnIkKqZYxjNHbOwR@cluster0.inh05rr.mongodb.net"
    build:
        context: . # Point to the root directory
        dockerfile: MediScreenApi/Dockerfile
    ports:
      - "600:80"
    networks:
      -  mediscreen-network


networks:
  mediscreen-network:
    driver: bridge
    
